apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    env: dev
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: REACT_APP_AUTH0_DOMAIN
              value: dev-3w4yg45y.eu.auth0.com
            - name: REACT_APP_AUTH0_CLIENT_ID
              value: zZax6BRHFDmrCC3AotFW1s4V3xVTGDtp
