FROM golang:1.15-alpine as builder
RUN apk add --no-cache make
WORKDIR /build
COPY . /build
RUN make build TARGET=svc/api

FROM golang:1.15-alpine
ENV APP_PORT 80
EXPOSE 80
COPY --from=builder /build/bin/app /app/app
CMD ["/app/app"]